[package]
name = "flux-desktop"
version = "0.1.0"
description = "An ode to the macOS Drift screensaver"
authors = ["Sander Melnikov <hey@sandydoo.me"]
repository = "https://github.com/sandydoo/flux/"
license = "MIT"
publish = false
edition = "2021"

[dependencies]
flux = { path = "../flux", version = "0.1" }
glow = "0.11.2"
glutin = "0.28.0"
serde_json = "1"
