[workspace]
resolver = "2"

members = [
    "flux",
    "flux-desktop",
    "flux-wasm"
]

[profile.release]
codegen-units = 1 # Allow further optimisations by disabling parallel compilation
lto = true # Enable link-time optimisations
opt-level = "s" # Optimise for size
panic = "abort" # Strip expensive panic unwinding code
strip = true # Remove debug symbols
